$(document).ready(function(){
    $(".click1").click(function(){
        $("#par1").slideToggle(2500);
        $(".hidden1").slideToggle(2100);
    });
    $(".click2").click(function(){
        $("#par2").slideToggle(2500);
        $(".hidden2").slideToggle(2500);
    });
    $(".click3").click(function(){
        $("#par3").slideToggle(2500);
        $(".hidden3").slideToggle(2500);
    });
    $("form#submitForm").submit(function(event){
        event.preventDefault();
        var name=$("#name").val();
        alert(  name + " Thank you for reaching out to us, you will recieve a feedback shortly!!!");
    });
    
    $(".row1").hover(function(){
        $(".imge1").css({"opacity":"0.2","transition":"3s"});
        $("#parid1").show();
    },
    function(){
        $(".imge1").css("opacity","1");
        $("#parid1").hide();
    });
    $(".row2").hover(function(){
        $(".imge2").css({"opacity":"0.2","transition":"3s"});
        $("#parid2").show();
    },
    function(){
        $(".imge2").css("opacity","1")
        $("#parid2").hide();
    });
    $(".row3").hover(function(){
        $(".imge3").css({"opacity":"0.2","transition":"3s"});
        $("#parid3").show();
    },
    function(){
        $(".imge3").css("opacity","1")
        $("#parid3").hide();
    });
    $(".row4").hover(function(){
        $(".imge4").css({"opacity":"0.2","transition":"3s"});
        $("#parid4").show();
    },
    function(){
        $(".imge4").css("opacity","1")
        $("#parid4").hide();
    });
    $(".row5").hover(function(){
        $(".imge5").css({"opacity":"0.2","transition":"3s"});
        $("#parid5").show();
    },
    function(){
        $(".imge5").css("opacity","1")
        $("#parid5").hide();
    });
    $(".row6").hover(function(){
        $(".imge6").css({"opacity":"0.2","transition":"3s"});
        $("#parid6").show();
    },
    function(){
        $(".imge6").css("opacity","1")
        $("#parid6").hide();
    });
    $(".row7").hover(function(){
        $(".imge7").css({"opacity":"0.2","transition":"3s"});
        $("#parid7").show();
    },
    function(){
        $(".imge7").css("opacity","1")
        $("#parid7").hide();
    });
    $(".row8").hover(function(){
        $(".imge8").css({"opacity":"0.2","transition":"3s"});
        $("#parid8").show();
    },
    function(){
        $(".imge8").css("opacity","1")
        $("#parid8").hide();
    });
});